# Generated by Django 3.1.2 on 2020-10-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=50, verbose_name='Nombre_de_calle.')),
                ('house_number', models.IntegerField(verbose_name='Numero_de_casa.')),
                ('reference', models.CharField(max_length=100, verbose_name='Referencia.')),
            ],
        ),
    ]
