# Generated by Django 3.1.2 on 2020-10-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_auto_20201023_0045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Puesto--Sueldo--Dias laborados', 'verbose_name_plural': 'Puestos'},
        ),
    ]
