# Generated by Django 3.1.2 on 2020-10-23 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_auto_20201023_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='house_number',
            field=models.PositiveIntegerField(verbose_name='Numero de casa.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Sueldo por día.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='working_day',
            field=models.PositiveIntegerField(verbose_name='Dias laborados.'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre.')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellidos.')),
                ('phone', models.CharField(max_length=13, verbose_name='Numero de telefono.')),
                ('direction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.direction', verbose_name='Dirección')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.task', verbose_name='Puesto')),
            ],
            options={
                'verbose_name': 'Empleado--Puesto',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
