# Generated by Django 3.1.2 on 2020-10-23 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0004_auto_20201023_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Puesto', 'verbose_name_plural': 'Puestos'},
        ),
    ]
