# Generated by Django 3.1.2 on 2020-11-11 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0005_auto_20201023_0106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
