# Generated by Django 3.1.2 on 2020-11-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0006_auto_20201110_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingre', models.PositiveIntegerField(verbose_name='Ingresos')),
                ('gast', models.PositiveIntegerField(verbose_name='Gastos')),
                ('cut', models.PositiveIntegerField(verbose_name='Fecha de corte:')),
            ],
            options={
                'verbose_name': 'Otro',
                'verbose_name_plural': 'Otras',
            },
        ),
    ]
