# Generated by Django 3.1.2 on 2020-11-11 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0009_odate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='odate_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nomina.odate', verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
